# Generated by Django 4.1.5 on 2023-02-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bio_customuser_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo_meme',
            field=models.URLField(null=True),
        ),
    ]
