# Generated by Django 4.1.5 on 2023-01-16 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='project',
            new_name='project_id',
        ),
    ]
