# Generated by Django 4.1.5 on 2023-01-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_project_pledge_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='project_id',
            new_name='project',
        ),
    ]
