# Generated by Django 4.1.5 on 2023-02-02 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_alter_pledge_supporter_likedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='liked_by',
        ),
        migrations.AlterField(
            model_name='likedby',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
