# Generated by Django 4.1.5 on 2023-02-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_project_liked_by_alter_likedby_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedby',
            old_name='User',
            new_name='liked_by',
        ),
    ]
