# Generated by Django 4.1.5 on 2023-02-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_pledge_amount_alter_pledge_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
