# Generated by Django 4.1.5 on 2023-02-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.PositiveIntegerField(),
        ),
    ]
